### ISSUE TITLE
Level Feature $

### ISSUE THREAD

**Issue by HeKaMe** [tim-we/Breakout#1]
$ macht noch nicht was es soll
Zeile wird zwar verschoben aber entweder landet der erste Block in der obersten Zeile oder die Zeile rückt in der YPos eine Zeile nach oben.

**Comment by tim-we** [comment]
Ich würd das nochmal komplett neu machen und vielleicht auch nochmal die Zeichen ändern. Ist wahrscheinlich einfacher wenn $ z.B. für eine einfache Lücke steht. Ich glaub '.' funktioniert in deiner aktuellen Implementierung auch nicht.

**Comment by HeKaMe** [comment]
hab das jetzt erstmal so wie gedacht umgesetzt, kannst es dir ja mal ansehen, hab damit auch mal ein CAU level erstellt also nachdem man sich ein wenig eingefunden hat geht das eigentlich ganz gut so
